### PR TITLE
Closing #165

### PR DESCRIPTION
**Pull request by akopachov**

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
Also, we do have #165 implemented already btw

**Comment by akopachov** [comment]
@ClaraCrazy you do, but without font preview, if I remember correctly. Apologies for lot of junk emails. Just want to make this f*ing auto-clang-format action to work :)

**Comment by ClaraCrazy** [comment]
thats true, we dont have preview. tbh, we just copied what unleashed made lmao

**Comment by akopachov** [comment]
@ClaraCrazy I've done one this. Thanks for the patience.

Also, it appeared that it is not that complicated to automatically apply clang-format for everything in a PR.

**Pull request merged**
